package resources;

public enum ACTION {
    DEFAULT,
    PRIDEJ_MINCI,
    VYPIS_MINCE, VYPIS_DOSTUPNOST, VYPIS_POUZIVANI,
    KUP_KAFE,
    ODEBER_VODU, PRIDEJ_VODU,
    ODEBER_CUKR, PRIDEJ_CUKR,
    ODEBER_KAFE, PRIDEJ_KAFE,
    ODEBER_KELIMEK, PRIDEJ_KELIMEK,
    VRAT_CHYBOVY_STAV,
    NEPLATNA_AKCE,
    PRAZDNA_PENEZENKA,
    VRAT_VSECHNY_PENIZE, VRAT_ZBYTEK,
    MAM_ROZMENENI, CHCI_PLATIT_VIC,
    VYDANI_KELIMKU,
    OHREVANI_VODY,
    ODSYPANI_KAVY,
    ODLEVANI,
    VYDANI_KAFE;
}
