package resources;

public enum STAV {
    START,
    SERVIS,
    PENEZENKA,
    NAPOJ_ZVOLEN,
    ROZMENENI,
    PLATIT_VIC,
    VYDEJ_KELIMEK,
    OHREV_VODY,
    ODSYP_KAVY,
    ODLITI_NAPOJE,
    VRATIT_ZBYTEK,
    VYDEJ_KAFE,
    VRATIT_PENIZE;
}
